### ISSUE TITLE
AGI version detection fails on systems with decimal comma

### ISSUE THREAD

**Issue by agren** [Deledrius/agistudio#3]
Hi,

I've found an issue where AGI Studio fails to detect the correct AGI version when opening a game. If the system uses decimal comma instead of decimal period.
I've made a fix. If you'd like I can make a pull request.

**System**
Ubuntu 16.04 x64

**Steps to reproduce**
1. Start AGIStudio with `LC_NUMERIC="sv_SE.UTF-8" ./AGIStudio`
2. Open a 2.917 game
3. Open a logic resource containing the action command 160 (Probably any command that isn't supported by version 2.0 should do it)

**Observed behaviour**
Opening the logic gives an error popup saying: "Unknown action command (160)".
And the logic resource code is not visible in the resources 'Preview' field.

**Expected behaviour**
No error message.
The logic resource code should be visible in the resources 'Preview' field.

**Fix**
I've made a fix that is locale independent here c33d7f8b0116e348b2299a5a1b8cb026ec717f54

**Workaround**
A workaround without using the above fix: Start AGI Studio using `LC_NUMERIC="en_US.UTF-8" AGIStudio`

**Comment by Deledrius** [comment]
Thanks for finding and reporting this bug.  It seems like a reasonable solution.  I'll just go ahead and merge in this commit since it's singular.

I notice you have a couple of other promising branches.  Feel free to open PRs for them when they're ready!

**Comment by Deledrius** [comment]
Closed by 567772d535dd8fb2f5095a5582e3731aae4617e5.
