### ISSUE TITLE
Error building on Linux

### ISSUE THREAD

**Issue by tmr83** [Deledrius/agistudio#4]
Hello,

I am getting this error after running make:

/home/user/agistudio/src/agiplay.cpp: In function ‘void play_sound(char*)’:
/home/user/agistudio/src/agiplay.cpp:265:17: error: aggregate ‘play_sound(char*)::stat buf’ has incomplete type and cannot be defined
  265 |     struct stat buf;
      |                 ^~~
/home/user/agistudio/src/agiplay.cpp:266:5: error: ‘fstat’ was not declared in this scope; did you mean ‘stat’?
  266 |     fstat(fileno(fptr), &buf);
      |     ^~~~~
      |     stat

I am not familiar with c++, so any help building would be appreciated.

**Comment by Deledrius** [comment]
Thanks for the bug report!  I haven't had time to work on this project for a while, but I'll try to look into this issue for you and have a better response soon. :)

**Comment by Deledrius** [comment]
Fixed by #5.
